### ISSUE TITLE
jQuery(...).lapstooltip is not a function

### ISSUE THREAD

**Issue by mckernanin** [Rarst/laps#18]
hey, I upgraded to laps 2.0, love the new stuff! On the front end of my site, while logged in, I'm getting an error about lapsTooltip not being defined:

<img width="408" alt="screenshot 2018-03-04 11 52 25" src="https://user-images.githubusercontent.com/6300047/36949218-8d1b6726-1fa2-11e8-9f2c-4fdec13ed3db.png">
<img width="562" alt="screenshot 2018-03-04 11 52 57" src="https://user-images.githubusercontent.com/6300047/36949224-99056dc0-1fa2-11e8-853d-b0072861e12b.png">

**Comment by Rarst** [comment]
Huh, that strange since you can literally see that getting set up mere two lines above.

You mention front end explicitly, does that mean that it works correctly in admin?

Did the previous version work properly? There hadn't actually been much change to how this is done in v2 (yet), it still uses Bootstrap v3 and mostly same JS build logic.

By chance is your front end doing anything like re-defining core jQuery version, loading multiple jQuery version or anything else like that?

**Comment by mckernanin** [comment]
Hey Andrey, I'll poke around and see if I can figure out exactly where the issue is.

**Comment by mckernanin** [comment]
Yeah, turns out the email list service we use injects jQuery 1.7.x in to the page. A page without an opt in form works just fine. 

🙄
