### ISSUE TITLE
Incompatibility with Wordfence

### ISSUE THREAD

**Issue by CimiGod** [Rarst/laps#21]
I have a 500 error if I active Wordfence 7.1.12 and Laps 2.0 togheter (PHP 7.0)

[19-Sep-2018 16:00:12 UTC] PHP Fatal error:  Uncaught Error: Class 'GeoIp2\Database\Reader' not found in /home2/liuck26416/public_html/wp-content/plugins/wordfence/models/common/wfGeoIP2.php:28
Stack trace:
#0 /home2/liuck26416/public_html/wp-content/plugins/wordfence/lib/wfUtils.php(1370): wfGeoIP2::shared()
#1 /home2/liuck26416/public_html/wp-content/plugins/wordfence/lib/wordfenceClass.php(1837): wfUtils::geoIPVersion()
#2 /home2/liuck26416/public_html/wp-includes/class-wp-hook.php(286): wordfence::veryFirstAction('')
#3 /home2/liuck26416/public_html/wp-includes/class-wp-hook.php(310): WP_Hook->apply_filters(NULL, Array)
#4 /home2/liuck26416/public_html/wp-includes/plugin.php(453): WP_Hook->do_action(Array)
#5 /home2/liuck26416/public_html/wp-settings.php(327): do_action('plugins_loaded')
#6 /home2/liuck26416/public_html/wp-config.php(101): require_once('/home2/liuck264...')
#7 /home2/liuck26416/public_html/wp-load.php(37): require_once('/home2/liuck264...')
#8 /home2/liuck26416/public_html/wp-admin/admin.php(31): require_once('/home2/liuck264...')
# in /home2/liuck26416/public_html/wp-content/plugins/wordfence/models/common/wfGeoIP2.php on line 28

I didn't investigate about problem, but surely is a problem on my server (2 sites with this problem since Wordfence upgrade).

If I disable Laps all works well.

**Comment by Rarst** [comment]
Cannot reproduce by just having Wordfence enabled. Can force the crash by explicit `wfGeoIP2::shared()` call in that method, but different error and that explodes _without_ Laps enabled.

Had you reported this to Wordfence as well? It might be some kind of exotic interaction between the plugins, but since _their_ stuff explodes I would start there. :)

Without being able to reproduce it I don't have anything to go by at the moment...

**Comment by slim16165** [comment]
If you like I can clone the webserver and give you the credential to access it as admin on my server. You could install whatever you want.

**Comment by Rarst** [comment]
Sorry, that is beyond the effort I can typically dedicate to troubleshooting.

**Comment by Rarst** [comment]
My best guess so far is that Wordfence autoload melts if there is another Composer `ClassLoader` preceding it _and_ something else going on to make it matter (since it works for me). They ship vendor directory for some dependencies, but it's not clear how exactly it's generated and kept up to date since their plugin itself doesn't use it for class load.

Typically I would recommend to install both plugins as part of Composer stack (which is recommended for Laps in first place), but I don't think this is going to make a difference here since Wordfence doesn't seem to support conventional Composer install (no `composer.json`).

**Comment by slim16165** [comment]
Thanks,
I will open a ticket to them.
ᐧ

Il giorno lun 12 nov 2018 alle ore 16:04 Andrey Savchenko <
notifications@github.com> ha scritto:

**Comment by Rarst** [comment]
I asked on twitter if there is anyone on their side who can take a look and they requested that I drop them details via email, which I did.

**Comment by slim16165** [comment]
Hi,
I guess wordlift wrote also to you about Updating to version 1.6 of composer

**Comment by Rarst** [comment]
No, I hadn't heard anything about Composer from them. It _could_ be Composer autoload conflict (which is precisely why recommended way to install Laps is Composer install with shared autoload).

**Comment by slim16165** [comment]
They said:
Hi Gianluigi,

We've tested this now and it appears to be happening ​because the Laps
plugin is using an older version of Composer's Classloader.php. Updating to
version 1.6 of composer which was released on 5 Jan should fix this.

Composer is a Linux tool? How can i do without root access?

Il giorno mer 14 nov 2018, 09:59 Andrey Savchenko <notifications@github.com>
ha scritto:

**Comment by Rarst** [comment]
Composer is easy to install on any platform and doesn't require root, see https://getcomposer.org/download/

To regenerate auto loader you would need to run `composer dump-autoload` in the Laps folder (if you downloaded standalone archive install to be clear for anyone else reading).

I _still_ cannot reproduce the issue, even if i specifically use that Laps archive released back then.

**Comment by slim16165** [comment]
Thanks!
(Btw if you want acces to the cloned server with the issue, just tell me a
private contact.)

Il giorno mer 14 nov 2018, 10:55 Andrey Savchenko <notifications@github.com>
ha scritto:

**Comment by Rarst** [comment]
Here is a build of Laps 2.0 with current stable Composer version (1.7.3) https://www.dropbox.com/s/6bkt93bgzlf4fsg/laps-2.0.zip

Could you please try this one and let me know if it resolves the issue for you?

**Comment by slim16165** [comment]
Yes, it works perfectly!
ᐧ

Il giorno mer 14 nov 2018 alle ore 11:36 Andrey Savchenko <
notifications@github.com> ha scritto:
