### ISSUE TITLE
MIT license?

### ISSUE THREAD

**Issue by vladlu** [Rarst/laps#26]
I wanted to use MIT license for my plugin too but found out that it's impossible because it uses WordPress (GPL) functionality.

Maybe am I missing something?

Some links:

* https://developer.wordpress.org/themes/getting-started/wordpress-licensing-the-gpl/#do-i-need-to-license-my-themes-under-the-gpl
* https://janelia-flyem.github.io/licenses.html

**Comment by Rarst** [comment]
WordPress project position on licensing of extensions is extremely inconsistent.

1. On one hand WP projects considers extensions to be derivative works under GPL which should be licensed under GPL.
2. On other hand official WP repositories state that extensions should use license merely [_compatible_ with GPL](https://developer.wordpress.org/plugins/wordpress-org/detailed-plugin-guidelines/#1-plugins-must-be-compatible-with-the-gnu-general-public-license), which directly contradicts them being derivatives under GPL.

De–facto there are thousands plugins licensed under MIT in the official repository.

My _personal_ position is that a long as I don’t copy/paste and directly use code from WordPress core my plugin is not a derivative work. As long as I use MIT (which I do whenever I can) this is consistent with WP plugin developer guidelines.

So frankly there is no “right” answer here because WP project’s position on this is broken and self–contradictory. I told you my reasoning, you would have to decide yourself for youw own plugins. :)
