### ISSUE TITLE
[Feature Request] Server Timings for synthetic tests

### ISSUE THREAD

**Issue by dhavalgshah** [Rarst/laps#34]
Currently, Laps only sends ServerTimings headers for AJAX and REST API requests.

However, there is a huge untapped opportunity in automated synthetic testings using WebPageTest or likes. If Laps can send Server Timings data header on these, often anonymous, requests then it would remove the blind-spot the usual TTFB metric creates.

Plotting what went at WP side along with front-end metrics can greatly improve the value of the performance reports.

## Implementation idea

A custom header or query string param with an auth token to be sent along with the request. Laps can verify the token and send the server timings data.

A config constant to enable or disable or to set auth token may be introduced.

This is just a suggestion. I would love to do a PR once the idea matures.

**Comment by Rarst** [comment]
To be honest Server Timings here is a bit of bolt on, because it's neither well suited for WP (lack of response processing layer) or (current) Laps architecture (single implicitly cached point of event collection). They are _headers_ and essentially it's impossible to make WP work neatly with them, without buffering and delaying sending the whole page to capture complete results. Which frankly I don't care to do from a plugin. There is a concept of trailing headers for this (sent _after_ the page body_), but apparently support for them is lacking and not really heading anywhere.

If you want to experiment with this, I suggest to build a standalone implementation on top of Laps. You can buffer the page yourself, yank full data from Laps, and emit as headers. I would be very open to hear if there are any roadblocks to having this be easy/extensible.

But _at the moment_ I am not interested in building out more of Server Timing functionality since essentially it's a secondary/inferior function to the main plugin interface.

**Comment by dhavalgshah** [comment]
You are right about the header and HTTP request handling issues with WP. I tried a number of ways to get this right over the weekend but couldn't find a reliable mechanism. Thank you for your work on Laps.

So for now, I am spiting the data as json object at `shutdown` if the request comes with a custom header. This is not an ideal approach but is working atm.
